//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
import type { EmojiCategory } from "./types";

export const animals: EmojiCategory = {
  label: "Animals & Nature",
  icon: "🐾",
  entries: [
    { emoji: "🐶", keywords: ["dog", "puppy", "pet"] },
    { emoji: "🐱", keywords: ["cat", "kitten", "pet"] },
    { emoji: "🐭", keywords: ["mouse", "rat"] },
    { emoji: "🐹", keywords: ["hamster", "pet"] },
    { emoji: "🐰", keywords: ["rabbit", "bunny"] },
    { emoji: "🦊", keywords: ["fox", "cunning"] },
    { emoji: "🐻", keywords: ["bear", "teddy"] },
    { emoji: "🐼", keywords: ["panda", "bear"] },
    { emoji: "🐻‍❄️", keywords: ["polar bear", "arctic"] },
    { emoji: "🐨", keywords: ["koala", "australia"] },
    { emoji: "🐯", keywords: ["tiger", "cat"] },
    { emoji: "🦁", keywords: ["lion", "king", "mane"] },
    { emoji: "🐮", keywords: ["cow", "moo"] },
    { emoji: "🐷", keywords: ["pig", "oink"] },
    { emoji: "🐸", keywords: ["frog", "toad"] },
    { emoji: "🐵", keywords: ["monkey", "ape"] },
    { emoji: "🙈", keywords: ["see no evil", "monkey"] },
    { emoji: "🙉", keywords: ["hear no evil", "monkey"] },
    { emoji: "🙊", keywords: ["speak no evil", "monkey"] },
    { emoji: "🐒", keywords: ["monkey", "primate"] },
    { emoji: "🐔", keywords: ["chicken", "hen", "poultry"] },
    { emoji: "🐧", keywords: ["penguin", "arctic", "cold"] },
    { emoji: "🐦", keywords: ["bird", "tweet"] },
    { emoji: "🐤", keywords: ["chick", "baby", "bird"] },
    { emoji: "🐣", keywords: ["hatching", "chick", "egg"] },
    { emoji: "🐥", keywords: ["chick", "bird", "baby"] },
    { emoji: "🦆", keywords: ["duck", "quack"] },
    { emoji: "🦅", keywords: ["eagle", "bird", "freedom"] },
    { emoji: "🦉", keywords: ["owl", "wise", "night"] },
    { emoji: "🦇", keywords: ["bat", "vampire", "night"] },
    { emoji: "🐺", keywords: ["wolf", "howl"] },
    { emoji: "🐗", keywords: ["boar", "wild pig"] },
    { emoji: "🐴", keywords: ["horse", "pony"] },
    { emoji: "🦄", keywords: ["unicorn", "magic", "fantasy"] },
    { emoji: "🫎", keywords: ["moose", "elk"] },
    { emoji: "🐝", keywords: ["bee", "honeybee", "buzz"] },
    { emoji: "🪱", keywords: ["worm"] },
    { emoji: "🐛", keywords: ["bug", "caterpillar", "insect"] },
    { emoji: "🦋", keywords: ["butterfly", "insect", "beautiful"] },
    { emoji: "🐌", keywords: ["snail", "slow"] },
    { emoji: "🐞", keywords: ["ladybug", "ladybird", "insect"] },
    { emoji: "🐜", keywords: ["ant", "insect"] },
    { emoji: "🪰", keywords: ["fly", "insect"] },
    { emoji: "🪲", keywords: ["beetle", "insect"] },
    { emoji: "🪳", keywords: ["cockroach", "bug"] },
    { emoji: "🦟", keywords: ["mosquito", "insect"] },
    { emoji: "🦗", keywords: ["cricket", "insect"] },
    { emoji: "🕷️", keywords: ["spider", "arachnid"] },
    { emoji: "🕸️", keywords: ["spider web", "cobweb"] },
    { emoji: "🦂", keywords: ["scorpion"] },
    { emoji: "🐢", keywords: ["turtle", "tortoise", "slow"] },
    { emoji: "🐍", keywords: ["snake", "reptile"] },
    { emoji: "🦎", keywords: ["lizard", "reptile"] },
    { emoji: "🦖", keywords: ["dinosaur", "t-rex", "trex"] },
    { emoji: "🦕", keywords: ["dinosaur", "sauropod", "brontosaurus"] },
    { emoji: "🐙", keywords: ["octopus", "sea"] },
    { emoji: "🦑", keywords: ["squid", "sea"] },
    { emoji: "🦐", keywords: ["shrimp", "prawn", "sea"] },
    { emoji: "🦞", keywords: ["lobster", "sea"] },
    { emoji: "🦀", keywords: ["crab", "sea"] },
    { emoji: "🪸", keywords: ["coral", "reef", "sea"] },
    { emoji: "🐡", keywords: ["blowfish", "puffer", "sea"] },
    { emoji: "🐠", keywords: ["tropical fish", "sea"] },
    { emoji: "🐟", keywords: ["fish", "sea"] },
    { emoji: "🐬", keywords: ["dolphin", "sea", "ocean"] },
    { emoji: "🐳", keywords: ["whale", "spout", "ocean"] },
    { emoji: "🐋", keywords: ["whale", "ocean"] },
    { emoji: "🦈", keywords: ["shark", "ocean", "jaws"] },
    { emoji: "🐊", keywords: ["crocodile", "alligator"] },
    { emoji: "🐅", keywords: ["tiger", "big cat"] },
    { emoji: "🐆", keywords: ["leopard", "cheetah"] },
    { emoji: "🦓", keywords: ["zebra", "stripes"] },
    { emoji: "🫏", keywords: ["donkey"] },
    { emoji: "🦍", keywords: ["gorilla", "ape"] },
    { emoji: "🦧", keywords: ["orangutan", "ape"] },
    { emoji: "🐘", keywords: ["elephant", "big"] },
    { emoji: "🦣", keywords: ["mammoth", "prehistoric"] },
    { emoji: "🦛", keywords: ["hippopotamus", "hippo"] },
    { emoji: "🦏", keywords: ["rhinoceros", "rhino"] },
    { emoji: "🐪", keywords: ["camel", "desert"] },
    { emoji: "🐫", keywords: ["camel", "two humps"] },
    { emoji: "🦒", keywords: ["giraffe", "tall"] },
    { emoji: "🦘", keywords: ["kangaroo", "australia"] },
    { emoji: "🦬", keywords: ["bison", "buffalo"] },
    { emoji: "🐃", keywords: ["water buffalo"] },
    { emoji: "🐂", keywords: ["ox", "bull"] },
    { emoji: "🐄", keywords: ["cow", "dairy"] },
    { emoji: "🐎", keywords: ["horse", "racing"] },
    { emoji: "🐖", keywords: ["pig", "hog"] },
    { emoji: "🐏", keywords: ["ram", "sheep"] },
    { emoji: "🐑", keywords: ["sheep", "lamb", "ewe"] },
    { emoji: "🦙", keywords: ["llama", "alpaca"] },
    { emoji: "🐐", keywords: ["goat"] },
    { emoji: "🦌", keywords: ["deer", "stag"] },
    { emoji: "🐕", keywords: ["dog", "pet"] },
    { emoji: "🐩", keywords: ["poodle", "dog"] },
    { emoji: "🦮", keywords: ["guide dog"] },
    { emoji: "🐕‍🦺", keywords: ["service dog"] },
    { emoji: "🐈", keywords: ["cat", "pet"] },
    { emoji: "🐈‍⬛", keywords: ["black cat"] },
    { emoji: "🪶", keywords: ["feather", "bird"] },
    { emoji: "🐓", keywords: ["rooster", "chicken"] },
    { emoji: "🦃", keywords: ["turkey", "thanksgiving"] },
    { emoji: "🦚", keywords: ["peacock", "bird"] },
    { emoji: "🦜", keywords: ["parrot", "bird", "tropical"] },
    { emoji: "🦢", keywords: ["swan", "bird", "elegant"] },
    { emoji: "🦩", keywords: ["flamingo", "pink"] },
    { emoji: "🕊️", keywords: ["dove", "peace", "bird"] },
    { emoji: "🐇", keywords: ["rabbit", "bunny"] },
    { emoji: "🦝", keywords: ["raccoon", "trash panda"] },
    { emoji: "🦨", keywords: ["skunk", "stink"] },
    { emoji: "🦡", keywords: ["badger"] },
    { emoji: "🦫", keywords: ["beaver", "dam"] },
    { emoji: "🦦", keywords: ["otter", "sea", "cute"] },
    { emoji: "🦥", keywords: ["sloth", "lazy", "slow"] },
    { emoji: "🐁", keywords: ["mouse", "rodent"] },
    { emoji: "🐀", keywords: ["rat", "rodent"] },
    { emoji: "🐿️", keywords: ["chipmunk", "squirrel"] },
    { emoji: "🦔", keywords: ["hedgehog", "prickly"] },
    { emoji: "🐾", keywords: ["paw prints", "pet", "animal"] },
    { emoji: "🐉", keywords: ["dragon", "fantasy"] },
    { emoji: "🐲", keywords: ["dragon face", "chinese"] },
    { emoji: "🌵", keywords: ["cactus", "desert"] },
    { emoji: "🎄", keywords: ["christmas tree", "holiday"] },
    { emoji: "🌲", keywords: ["evergreen", "tree", "pine"] },
    { emoji: "🌳", keywords: ["deciduous tree", "tree"] },
    { emoji: "🌴", keywords: ["palm tree", "tropical", "beach"] },
    { emoji: "🪵", keywords: ["wood", "log"] },
    { emoji: "🌱", keywords: ["seedling", "grow", "plant"] },
    { emoji: "🌿", keywords: ["herb", "plant", "green"] },
    { emoji: "☘️", keywords: ["shamrock", "clover", "irish"] },
    { emoji: "🍀", keywords: ["four leaf clover", "lucky", "luck"] },
    { emoji: "🎍", keywords: ["bamboo", "decoration"] },
    { emoji: "🪴", keywords: ["potted plant", "houseplant"] },
    { emoji: "🎋", keywords: ["tanabata tree"] },
    { emoji: "🍃", keywords: ["leaf", "wind", "nature"] },
    { emoji: "🍂", keywords: ["fallen leaf", "autumn", "fall"] },
    { emoji: "🍁", keywords: ["maple leaf", "canada", "fall"] },
    { emoji: "🪺", keywords: ["nest with eggs", "bird"] },
    { emoji: "🪹", keywords: ["empty nest"] },
    { emoji: "🍄", keywords: ["mushroom", "fungi"] },
    { emoji: "🌾", keywords: ["rice", "grain", "plant"] },
    { emoji: "💐", keywords: ["bouquet", "flowers"] },
    { emoji: "🌷", keywords: ["tulip", "flower", "spring"] },
    { emoji: "🌹", keywords: ["rose", "flower", "love"] },
    { emoji: "🥀", keywords: ["wilted flower", "dead"] },
    { emoji: "🪻", keywords: ["hyacinth", "flower"] },
    { emoji: "🌺", keywords: ["hibiscus", "flower", "tropical"] },
    { emoji: "🌸", keywords: ["cherry blossom", "flower", "spring"] },
    { emoji: "🌼", keywords: ["blossom", "flower"] },
    { emoji: "🌻", keywords: ["sunflower", "flower"] },
    { emoji: "🌞", keywords: ["sun with face", "sunny"] },
    { emoji: "🌝", keywords: ["moon with face", "night"] },
    { emoji: "🌛", keywords: ["first quarter moon face"] },
    { emoji: "🌜", keywords: ["last quarter moon face"] },
    { emoji: "🌚", keywords: ["new moon face", "creepy"] },
    { emoji: "🌕", keywords: ["full moon"] },
    { emoji: "🌖", keywords: ["waning gibbous moon"] },
    { emoji: "🌗", keywords: ["last quarter moon"] },
    { emoji: "🌘", keywords: ["waning crescent moon"] },
    { emoji: "🌑", keywords: ["new moon"] },
    { emoji: "🌒", keywords: ["waxing crescent moon"] },
    { emoji: "🌓", keywords: ["first quarter moon"] },
    { emoji: "🌔", keywords: ["waxing gibbous moon"] },
    { emoji: "🌙", keywords: ["crescent moon", "night"] },
    {
      emoji: "🌍",
      keywords: ["globe", "earth", "europe", "africa", "world"],
    },
    { emoji: "🌎", keywords: ["globe", "earth", "americas", "world"] },
    { emoji: "🌏", keywords: ["globe", "earth", "asia", "world"] },
    { emoji: "🪐", keywords: ["planet", "saturn", "ring", "space"] },
    { emoji: "💫", keywords: ["dizzy", "star", "shooting"] },
    { emoji: "⭐", keywords: ["star", "yellow"] },
    { emoji: "🌟", keywords: ["glowing star", "sparkle"] },
    { emoji: "✨", keywords: ["sparkles", "magic", "clean"] },
    { emoji: "⚡", keywords: ["lightning", "bolt", "electricity", "zap"] },
    { emoji: "☄️", keywords: ["comet", "meteor"] },
    { emoji: "💥", keywords: ["boom", "collision", "explosion"] },
    { emoji: "🔥", keywords: ["fire", "hot", "lit"] },
    { emoji: "🌪️", keywords: ["tornado", "twister"] },
    { emoji: "🌈", keywords: ["rainbow", "colorful"] },
    { emoji: "☀️", keywords: ["sun", "sunny", "bright"] },
    { emoji: "🌤️", keywords: ["sun behind small cloud"] },
    { emoji: "⛅", keywords: ["sun behind cloud"] },
    { emoji: "🌥️", keywords: ["sun behind large cloud"] },
    { emoji: "☁️", keywords: ["cloud", "overcast"] },
    { emoji: "🌦️", keywords: ["sun behind rain cloud"] },
    { emoji: "🌧️", keywords: ["rain", "cloud with rain"] },
    { emoji: "⛈️", keywords: ["thunder", "storm", "lightning"] },
    { emoji: "🌩️", keywords: ["cloud with lightning"] },
    { emoji: "🌨️", keywords: ["cloud with snow"] },
    { emoji: "❄️", keywords: ["snowflake", "cold", "winter"] },
    { emoji: "☃️", keywords: ["snowman", "winter", "cold"] },
    { emoji: "⛄", keywords: ["snowman", "winter"] },
    { emoji: "🌬️", keywords: ["wind", "blow", "face"] },
    { emoji: "💨", keywords: ["dash", "wind", "fast"] },
    { emoji: "💧", keywords: ["droplet", "water", "sweat"] },
    { emoji: "💦", keywords: ["sweat droplets", "water", "splash"] },
    { emoji: "🌊", keywords: ["wave", "ocean", "water", "sea"] },
    { emoji: "🫧", keywords: ["bubbles", "soap"] },
  ],
};
