//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
import type { EmojiCategory } from "./types";

export const food: EmojiCategory = {
  label: "Food & Drink",
  icon: "🍔",
  entries: [
    { emoji: "🍏", keywords: ["green apple", "fruit"] },
    { emoji: "🍎", keywords: ["red apple", "fruit"] },
    { emoji: "🍐", keywords: ["pear", "fruit"] },
    { emoji: "🍊", keywords: ["orange", "tangerine", "fruit"] },
    { emoji: "🍋", keywords: ["lemon", "citrus", "fruit"] },
    { emoji: "🍌", keywords: ["banana", "fruit"] },
    { emoji: "🍉", keywords: ["watermelon", "fruit", "summer"] },
    { emoji: "🍇", keywords: ["grapes", "fruit", "wine"] },
    { emoji: "🍓", keywords: ["strawberry", "fruit", "berry"] },
    { emoji: "🫐", keywords: ["blueberries", "fruit", "berry"] },
    { emoji: "🍈", keywords: ["melon", "fruit"] },
    { emoji: "🍒", keywords: ["cherries", "fruit"] },
    { emoji: "🍑", keywords: ["peach", "fruit"] },
    { emoji: "🥭", keywords: ["mango", "fruit", "tropical"] },
    { emoji: "🍍", keywords: ["pineapple", "fruit", "tropical"] },
    { emoji: "🥥", keywords: ["coconut", "tropical"] },
    { emoji: "🥝", keywords: ["kiwi", "fruit"] },
    { emoji: "🍅", keywords: ["tomato", "vegetable"] },
    { emoji: "🍆", keywords: ["eggplant", "aubergine"] },
    { emoji: "🥑", keywords: ["avocado", "guacamole"] },
    { emoji: "🫛", keywords: ["pea pod", "vegetable"] },
    { emoji: "🥦", keywords: ["broccoli", "vegetable"] },
    { emoji: "🥬", keywords: ["leafy green", "lettuce", "vegetable"] },
    { emoji: "🥒", keywords: ["cucumber", "pickle"] },
    { emoji: "🌶️", keywords: ["hot pepper", "spicy", "chili"] },
    { emoji: "🫑", keywords: ["bell pepper", "capsicum"] },
    { emoji: "🌽", keywords: ["corn", "maize"] },
    { emoji: "🥕", keywords: ["carrot", "vegetable"] },
    { emoji: "🫒", keywords: ["olive", "oil"] },
    { emoji: "🧄", keywords: ["garlic"] },
    { emoji: "🧅", keywords: ["onion"] },
    { emoji: "🥔", keywords: ["potato", "vegetable"] },
    { emoji: "🍠", keywords: ["sweet potato", "yam"] },
    { emoji: "🫘", keywords: ["beans"] },
    { emoji: "🥐", keywords: ["croissant", "bread", "french"] },
    { emoji: "🍞", keywords: ["bread", "toast", "loaf"] },
    { emoji: "🥖", keywords: ["baguette", "french bread"] },
    { emoji: "🫓", keywords: ["flatbread", "naan", "pita"] },
    { emoji: "🥨", keywords: ["pretzel", "snack"] },
    { emoji: "🥯", keywords: ["bagel", "bread"] },
    { emoji: "🥞", keywords: ["pancakes", "breakfast"] },
    { emoji: "🧇", keywords: ["waffle", "breakfast"] },
    { emoji: "🧀", keywords: ["cheese", "wedge"] },
    { emoji: "🍖", keywords: ["meat", "bone", "drumstick"] },
    { emoji: "🍗", keywords: ["poultry", "chicken leg"] },
    { emoji: "🥩", keywords: ["steak", "meat", "beef"] },
    { emoji: "🥓", keywords: ["bacon", "meat", "breakfast"] },
    { emoji: "🍔", keywords: ["hamburger", "burger", "fast food"] },
    { emoji: "🍟", keywords: ["french fries", "fries", "fast food"] },
    { emoji: "🍕", keywords: ["pizza", "slice"] },
    { emoji: "🌭", keywords: ["hot dog", "sausage"] },
    { emoji: "🥪", keywords: ["sandwich", "sub"] },
    { emoji: "🌮", keywords: ["taco", "mexican"] },
    { emoji: "🌯", keywords: ["burrito", "wrap", "mexican"] },
    { emoji: "🫔", keywords: ["tamale", "mexican"] },
    { emoji: "🥙", keywords: ["pita", "falafel", "kebab"] },
    { emoji: "🧆", keywords: ["falafel"] },
    { emoji: "🥚", keywords: ["egg"] },
    { emoji: "🍳", keywords: ["cooking", "fried egg", "breakfast"] },
    { emoji: "🥘", keywords: ["shallow pan", "paella", "cooking"] },
    { emoji: "🍲", keywords: ["pot", "stew", "soup"] },
    { emoji: "🫕", keywords: ["fondue", "cheese", "chocolate"] },
    { emoji: "🥣", keywords: ["bowl with spoon", "cereal"] },
    { emoji: "🥗", keywords: ["salad", "green", "healthy"] },
    { emoji: "🍿", keywords: ["popcorn", "movie", "snack"] },
    { emoji: "🧈", keywords: ["butter"] },
    { emoji: "🧂", keywords: ["salt", "seasoning"] },
    { emoji: "🥫", keywords: ["canned food", "tin"] },
    { emoji: "🍱", keywords: ["bento box", "japanese", "lunch"] },
    { emoji: "🍘", keywords: ["rice cracker", "japanese"] },
    { emoji: "🍙", keywords: ["rice ball", "onigiri", "japanese"] },
    { emoji: "🍚", keywords: ["cooked rice"] },
    { emoji: "🍛", keywords: ["curry rice", "indian"] },
    { emoji: "🍜", keywords: ["steaming bowl", "noodles", "ramen"] },
    { emoji: "🍝", keywords: ["spaghetti", "pasta", "italian"] },
    { emoji: "🍠", keywords: ["roasted sweet potato"] },
    { emoji: "🍢", keywords: ["oden", "skewer", "japanese"] },
    { emoji: "🍣", keywords: ["sushi", "japanese", "fish"] },
    { emoji: "🍤", keywords: ["fried shrimp", "tempura"] },
    { emoji: "🍥", keywords: ["fish cake", "narutomaki"] },
    { emoji: "🥮", keywords: ["moon cake", "chinese"] },
    { emoji: "🍡", keywords: ["dango", "japanese", "sweet"] },
    { emoji: "🥟", keywords: ["dumpling", "gyoza", "pierogi"] },
    { emoji: "🥠", keywords: ["fortune cookie"] },
    { emoji: "🥡", keywords: ["takeout box", "chinese food"] },
    { emoji: "🦀", keywords: ["crab", "seafood"] },
    { emoji: "🦞", keywords: ["lobster", "seafood"] },
    { emoji: "🦐", keywords: ["shrimp", "prawn", "seafood"] },
    { emoji: "🦑", keywords: ["squid", "calamari"] },
    { emoji: "🍦", keywords: ["ice cream", "soft serve", "dessert"] },
    { emoji: "🍧", keywords: ["shaved ice", "dessert"] },
    { emoji: "🍨", keywords: ["ice cream", "dessert", "sundae"] },
    { emoji: "🍩", keywords: ["doughnut", "donut", "dessert"] },
    { emoji: "🍪", keywords: ["cookie", "biscuit", "dessert"] },
    { emoji: "🎂", keywords: ["birthday cake", "celebration"] },
    { emoji: "🍰", keywords: ["cake", "shortcake", "dessert"] },
    { emoji: "🧁", keywords: ["cupcake", "muffin", "dessert"] },
    { emoji: "🥧", keywords: ["pie", "dessert"] },
    { emoji: "🍫", keywords: ["chocolate", "candy", "dessert"] },
    { emoji: "🍬", keywords: ["candy", "sweet"] },
    { emoji: "🍭", keywords: ["lollipop", "candy", "sweet"] },
    { emoji: "🍮", keywords: ["custard", "pudding", "flan"] },
    { emoji: "🍯", keywords: ["honey", "pot", "sweet"] },
    { emoji: "🍼", keywords: ["baby bottle", "milk"] },
    { emoji: "🥛", keywords: ["glass of milk", "dairy"] },
    { emoji: "☕", keywords: ["coffee", "hot", "tea", "drink"] },
    { emoji: "🫖", keywords: ["teapot", "tea"] },
    { emoji: "🍵", keywords: ["tea", "green tea", "drink"] },
    { emoji: "🧋", keywords: ["bubble tea", "boba", "drink"] },
    { emoji: "🍶", keywords: ["sake", "japanese", "drink"] },
    { emoji: "🍾", keywords: ["champagne", "bottle", "celebrate"] },
    { emoji: "🍷", keywords: ["wine", "glass", "drink"] },
    { emoji: "🍸", keywords: ["cocktail", "martini", "drink"] },
    { emoji: "🍹", keywords: ["tropical drink", "cocktail"] },
    { emoji: "🍺", keywords: ["beer", "mug", "drink"] },
    { emoji: "🍻", keywords: ["clinking beer mugs", "cheers"] },
    {
      emoji: "🥂",
      keywords: ["clinking glasses", "champagne", "cheers", "toast"],
    },
    { emoji: "🥃", keywords: ["tumbler", "whiskey", "drink"] },
    { emoji: "🫗", keywords: ["pouring liquid", "water"] },
    { emoji: "🥤", keywords: ["cup with straw", "soda", "drink"] },
    { emoji: "🧊", keywords: ["ice", "cube", "cold"] },
    { emoji: "🧃", keywords: ["juice box", "drink"] },
    { emoji: "🥤", keywords: ["cup with straw", "soda"] },
  ],
};
