//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
import type { EmojiCategory } from "./types";

export const gestures: EmojiCategory = {
  label: "Hands & Body",
  icon: "👋",
  entries: [
    { emoji: "👋", keywords: ["wave", "hello", "bye", "hand"] },
    { emoji: "🤚", keywords: ["raised back", "hand", "stop"] },
    { emoji: "🖐️", keywords: ["hand", "fingers", "splayed"] },
    { emoji: "✋", keywords: ["raised hand", "high five", "stop"] },
    { emoji: "🖖", keywords: ["vulcan", "spock", "star trek"] },
    { emoji: "🫱", keywords: ["rightward hand"] },
    { emoji: "🫲", keywords: ["leftward hand"] },
    { emoji: "🫳", keywords: ["palm down hand"] },
    { emoji: "🫴", keywords: ["palm up hand"] },
    { emoji: "🫷", keywords: ["leftward pushing hand"] },
    { emoji: "🫸", keywords: ["rightward pushing hand"] },
    { emoji: "👌", keywords: ["ok", "perfect", "fine"] },
    { emoji: "🤌", keywords: ["pinched fingers", "italian"] },
    { emoji: "🤏", keywords: ["pinching", "small", "tiny", "little"] },
    { emoji: "✌️", keywords: ["victory", "peace", "two"] },
    { emoji: "🤞", keywords: ["crossed fingers", "luck", "hope"] },
    { emoji: "🫰", keywords: ["hand with index finger and thumb crossed"] },
    { emoji: "🤟", keywords: ["love you", "ily", "hand"] },
    { emoji: "🤘", keywords: ["rock on", "metal", "horns"] },
    { emoji: "🤙", keywords: ["call me", "shaka", "hang loose"] },
    { emoji: "👈", keywords: ["point left", "direction"] },
    { emoji: "👉", keywords: ["point right", "direction"] },
    { emoji: "👆", keywords: ["point up", "direction"] },
    { emoji: "🖕", keywords: ["middle finger"] },
    { emoji: "👇", keywords: ["point down", "direction"] },
    { emoji: "☝️", keywords: ["index", "point up"] },
    { emoji: "🫵", keywords: ["index pointing at viewer", "you"] },
    { emoji: "👍", keywords: ["thumbs up", "like", "approve", "yes"] },
    { emoji: "👎", keywords: ["thumbs down", "dislike", "no"] },
    { emoji: "✊", keywords: ["raised fist", "power"] },
    { emoji: "👊", keywords: ["fist bump", "punch"] },
    { emoji: "🤛", keywords: ["left fist bump"] },
    { emoji: "🤜", keywords: ["right fist bump"] },
    { emoji: "👏", keywords: ["clap", "applause", "bravo"] },
    { emoji: "🙌", keywords: ["raising hands", "hooray", "celebrate"] },
    { emoji: "🫶", keywords: ["heart hands", "love"] },
    { emoji: "👐", keywords: ["open hands", "jazz hands"] },
    { emoji: "🤲", keywords: ["palms up", "prayer", "cupped"] },
    { emoji: "🤝", keywords: ["handshake", "deal", "agreement"] },
    { emoji: "🙏", keywords: ["pray", "please", "thank you", "namaste"] },
    { emoji: "✍️", keywords: ["writing", "hand"] },
    { emoji: "💅", keywords: ["nail polish", "beauty", "nails"] },
    { emoji: "🤳", keywords: ["selfie", "phone", "photo"] },
    { emoji: "💪", keywords: ["muscle", "strong", "flex", "bicep"] },
    { emoji: "🦾", keywords: ["mechanical arm", "prosthetic", "robot"] },
    { emoji: "🦿", keywords: ["mechanical leg", "prosthetic"] },
    { emoji: "🦵", keywords: ["leg", "kick"] },
    { emoji: "🦶", keywords: ["foot", "kick"] },
    { emoji: "👂", keywords: ["ear", "listen", "hear"] },
    { emoji: "🦻", keywords: ["ear with hearing aid"] },
    { emoji: "👃", keywords: ["nose", "smell"] },
    { emoji: "🧠", keywords: ["brain", "smart", "think", "intelligent"] },
    { emoji: "🫀", keywords: ["anatomical heart", "organ"] },
    { emoji: "🫁", keywords: ["lungs", "breathe"] },
    { emoji: "🦷", keywords: ["tooth", "dentist"] },
    { emoji: "🦴", keywords: ["bone", "skeleton"] },
    { emoji: "👀", keywords: ["eyes", "look", "see", "watching"] },
    { emoji: "👁️", keywords: ["eye", "see", "look"] },
    { emoji: "👅", keywords: ["tongue", "taste", "lick"] },
    { emoji: "👄", keywords: ["mouth", "lips", "kiss"] },
    { emoji: "🫦", keywords: ["biting lip", "nervous", "flirt"] },
    { emoji: "👶", keywords: ["baby", "infant", "child"] },
    { emoji: "🧒", keywords: ["child", "kid"] },
    { emoji: "👦", keywords: ["boy", "male", "child"] },
    { emoji: "👧", keywords: ["girl", "female", "child"] },
    { emoji: "🧑", keywords: ["person", "adult"] },
    { emoji: "👱", keywords: ["blond", "blonde", "person"] },
    { emoji: "👨", keywords: ["man", "male", "guy"] },
    { emoji: "🧔", keywords: ["beard", "man"] },
    { emoji: "👩", keywords: ["woman", "female", "lady"] },
    { emoji: "🧓", keywords: ["older person", "elder"] },
    { emoji: "👴", keywords: ["old man", "grandfather"] },
    { emoji: "👵", keywords: ["old woman", "grandmother"] },
    { emoji: "🙍", keywords: ["person frowning", "sad"] },
    { emoji: "🙎", keywords: ["person pouting", "annoyed"] },
    { emoji: "🙅", keywords: ["person gesturing no", "stop"] },
    { emoji: "🙆", keywords: ["person gesturing ok"] },
    { emoji: "💁", keywords: ["person tipping hand", "info"] },
    { emoji: "🙋", keywords: ["person raising hand", "question"] },
    { emoji: "🧏", keywords: ["deaf person"] },
    { emoji: "🙇", keywords: ["person bowing", "sorry"] },
    { emoji: "🤦", keywords: ["facepalm", "smh", "disbelief"] },
    { emoji: "🤷", keywords: ["shrug", "idk", "dunno", "whatever"] },
    { emoji: "🧑‍⚕️", keywords: ["health worker", "doctor", "nurse"] },
    { emoji: "🧑‍🎓", keywords: ["student", "graduate"] },
    { emoji: "🧑‍🏫", keywords: ["teacher", "professor"] },
    {
      emoji: "🧑‍💻",
      keywords: ["technologist", "programmer", "coder", "developer"],
    },
    { emoji: "🧑‍🔬", keywords: ["scientist", "researcher"] },
    { emoji: "🧑‍🎨", keywords: ["artist", "painter"] },
    { emoji: "🧑‍🚀", keywords: ["astronaut", "space"] },
    { emoji: "🧑‍🚒", keywords: ["firefighter"] },
    { emoji: "👮", keywords: ["police", "officer", "cop"] },
    { emoji: "🕵️", keywords: ["detective", "spy"] },
    { emoji: "💂", keywords: ["guard", "royal"] },
    { emoji: "🥷", keywords: ["ninja", "stealth"] },
    { emoji: "👷", keywords: ["construction worker", "builder"] },
    { emoji: "🫅", keywords: ["person with crown", "royalty"] },
    { emoji: "🤴", keywords: ["prince", "royalty"] },
    { emoji: "👸", keywords: ["princess", "royalty"] },
    { emoji: "🧙", keywords: ["mage", "wizard", "magic"] },
    { emoji: "🧚", keywords: ["fairy", "magic"] },
    { emoji: "🧛", keywords: ["vampire", "dracula"] },
    { emoji: "🧜", keywords: ["merperson", "mermaid"] },
    { emoji: "🧝", keywords: ["elf", "fantasy"] },
    { emoji: "🧞", keywords: ["genie", "magic", "lamp"] },
    { emoji: "🧟", keywords: ["zombie", "undead"] },
    { emoji: "🧌", keywords: ["troll"] },
    { emoji: "💆", keywords: ["person getting massage", "relax"] },
    { emoji: "💇", keywords: ["person getting haircut", "salon"] },
    { emoji: "🚶", keywords: ["person walking"] },
    { emoji: "🧍", keywords: ["person standing"] },
    { emoji: "🧎", keywords: ["person kneeling"] },
    { emoji: "🏃", keywords: ["person running", "exercise"] },
    { emoji: "💃", keywords: ["woman dancing", "dance"] },
    { emoji: "🕺", keywords: ["man dancing", "dance", "disco"] },
    { emoji: "👯", keywords: ["people with bunny ears", "dancers"] },
    { emoji: "🧖", keywords: ["person in steamy room", "sauna"] },
    { emoji: "🧗", keywords: ["person climbing", "rock"] },
    { emoji: "🤸", keywords: ["person cartwheeling", "gymnastics"] },
    { emoji: "🏌️", keywords: ["person golfing", "golf"] },
    { emoji: "🏇", keywords: ["horse racing", "jockey"] },
    { emoji: "⛷️", keywords: ["skier", "skiing", "snow"] },
    { emoji: "🏂", keywords: ["snowboarder", "snow", "winter"] },
    { emoji: "🏋️", keywords: ["person lifting weights", "gym"] },
    { emoji: "🤼", keywords: ["people wrestling"] },
    { emoji: "🤽", keywords: ["person playing water polo"] },
    { emoji: "🤾", keywords: ["person playing handball"] },
    { emoji: "🤺", keywords: ["person fencing", "sword"] },
    { emoji: "⛹️", keywords: ["person bouncing ball", "basketball"] },
    { emoji: "🏊", keywords: ["person swimming", "pool"] },
    { emoji: "🚣", keywords: ["person rowing boat"] },
    {
      emoji: "🧘",
      keywords: ["person in lotus position", "yoga", "meditate"],
    },
    { emoji: "🛀", keywords: ["person taking bath", "bathtub"] },
    { emoji: "🛌", keywords: ["person in bed", "sleeping"] },
    { emoji: "👭", keywords: ["women holding hands"] },
    { emoji: "👫", keywords: ["woman and man holding hands", "couple"] },
    { emoji: "👬", keywords: ["men holding hands"] },
    { emoji: "💏", keywords: ["kiss", "couple"] },
    { emoji: "💑", keywords: ["couple with heart", "love"] },
    { emoji: "👪", keywords: ["family"] },
    { emoji: "🗣️", keywords: ["speaking head", "talking"] },
    { emoji: "👤", keywords: ["bust", "silhouette", "person"] },
    { emoji: "👥", keywords: ["busts", "silhouettes", "people", "group"] },
    { emoji: "🫂", keywords: ["people hugging", "hug", "embrace"] },
    { emoji: "👣", keywords: ["footprints", "feet", "tracks"] },
  ],
};
