//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
import type { EmojiCategory } from "./types";

export const objects: EmojiCategory = {
  label: "Objects",
  icon: "💡",
  entries: [
    { emoji: "⌚", keywords: ["watch", "time"] },
    { emoji: "📱", keywords: ["phone", "mobile", "cell", "smartphone"] },
    { emoji: "📲", keywords: ["phone", "call", "incoming"] },
    { emoji: "💻", keywords: ["laptop", "computer", "pc"] },
    { emoji: "⌨️", keywords: ["keyboard", "type"] },
    { emoji: "🖥️", keywords: ["desktop computer", "monitor"] },
    { emoji: "🖨️", keywords: ["printer"] },
    { emoji: "🖱️", keywords: ["computer mouse"] },
    { emoji: "🖲️", keywords: ["trackball"] },
    { emoji: "💽", keywords: ["computer disk", "minidisk"] },
    { emoji: "💾", keywords: ["floppy disk", "save"] },
    { emoji: "💿", keywords: ["cd", "disk", "optical"] },
    { emoji: "📀", keywords: ["dvd", "disk"] },
    { emoji: "📷", keywords: ["camera", "photo"] },
    { emoji: "📸", keywords: ["camera with flash", "photo"] },
    { emoji: "📹", keywords: ["video camera", "camcorder"] },
    { emoji: "🎥", keywords: ["movie camera", "film"] },
    { emoji: "📽️", keywords: ["film projector"] },
    { emoji: "🎞️", keywords: ["film frames", "movie"] },
    { emoji: "📞", keywords: ["telephone", "call"] },
    { emoji: "☎️", keywords: ["telephone", "call", "phone"] },
    { emoji: "📟", keywords: ["pager", "beeper"] },
    { emoji: "📠", keywords: ["fax machine"] },
    { emoji: "📺", keywords: ["television", "tv", "screen"] },
    { emoji: "📻", keywords: ["radio", "music"] },
    { emoji: "🎙️", keywords: ["studio microphone", "podcast"] },
    { emoji: "🎚️", keywords: ["level slider", "volume"] },
    { emoji: "🎛️", keywords: ["control knobs", "dials"] },
    { emoji: "🧭", keywords: ["compass", "navigation"] },
    { emoji: "⏱️", keywords: ["stopwatch", "timer"] },
    { emoji: "⏲️", keywords: ["timer clock"] },
    { emoji: "⏰", keywords: ["alarm clock", "wake up"] },
    { emoji: "🕰️", keywords: ["mantelpiece clock"] },
    { emoji: "⌛", keywords: ["hourglass", "time", "sand"] },
    { emoji: "⏳", keywords: ["hourglass flowing", "time"] },
    { emoji: "🔋", keywords: ["battery", "power", "charge"] },
    { emoji: "🪫", keywords: ["low battery"] },
    { emoji: "🔌", keywords: ["plug", "electric", "power"] },
    { emoji: "💡", keywords: ["light bulb", "idea", "bright"] },
    { emoji: "🔦", keywords: ["flashlight", "torch"] },
    { emoji: "🕯️", keywords: ["candle", "light", "flame"] },
    { emoji: "🧯", keywords: ["fire extinguisher"] },
    { emoji: "🗑️", keywords: ["wastebasket", "trash", "delete"] },
    { emoji: "🛢️", keywords: ["oil drum", "barrel"] },
    { emoji: "💸", keywords: ["money with wings", "spending"] },
    { emoji: "💵", keywords: ["dollar", "money", "cash"] },
    { emoji: "💴", keywords: ["yen", "money"] },
    { emoji: "💶", keywords: ["euro", "money"] },
    { emoji: "💷", keywords: ["pound", "money"] },
    { emoji: "🪙", keywords: ["coin", "money"] },
    { emoji: "💰", keywords: ["money bag", "rich", "cash"] },
    { emoji: "💳", keywords: ["credit card", "payment"] },
    { emoji: "💎", keywords: ["gem", "diamond", "jewel"] },
    { emoji: "⚖️", keywords: ["balance scale", "justice"] },
    { emoji: "🪜", keywords: ["ladder", "climb"] },
    { emoji: "🧰", keywords: ["toolbox", "tools"] },
    { emoji: "🪛", keywords: ["screwdriver", "tool"] },
    { emoji: "🔧", keywords: ["wrench", "tool", "settings"] },
    { emoji: "🔨", keywords: ["hammer", "tool", "build"] },
    { emoji: "⚒️", keywords: ["hammer and pick", "tool"] },
    { emoji: "🛠️", keywords: ["hammer and wrench", "tools"] },
    { emoji: "⛏️", keywords: ["pick", "mining"] },
    { emoji: "🪚", keywords: ["saw", "carpentry"] },
    { emoji: "🔩", keywords: ["nut and bolt", "hardware"] },
    { emoji: "⚙️", keywords: ["gear", "settings", "cog"] },
    { emoji: "🪤", keywords: ["mouse trap"] },
    { emoji: "🧲", keywords: ["magnet", "attract"] },
    { emoji: "🔫", keywords: ["water gun", "pistol", "squirt"] },
    { emoji: "💣", keywords: ["bomb", "explosive"] },
    { emoji: "🧨", keywords: ["firecracker", "dynamite"] },
    { emoji: "🪓", keywords: ["axe", "chop"] },
    { emoji: "🔪", keywords: ["kitchen knife", "cut"] },
    { emoji: "🗡️", keywords: ["dagger", "sword"] },
    { emoji: "⚔️", keywords: ["crossed swords", "battle"] },
    { emoji: "🛡️", keywords: ["shield", "defense", "protect"] },
    { emoji: "🔑", keywords: ["key", "lock", "password"] },
    { emoji: "🗝️", keywords: ["old key", "vintage"] },
    { emoji: "🔒", keywords: ["lock", "locked", "secure", "privacy"] },
    { emoji: "🔓", keywords: ["unlocked", "open"] },
    { emoji: "🔏", keywords: ["lock with pen", "privacy"] },
    { emoji: "🔐", keywords: ["locked with key", "secure"] },
    { emoji: "📧", keywords: ["email", "e-mail", "envelope"] },
    { emoji: "✉️", keywords: ["envelope", "mail", "letter"] },
    { emoji: "📨", keywords: ["incoming envelope", "email"] },
    { emoji: "📩", keywords: ["envelope with arrow", "email"] },
    { emoji: "📤", keywords: ["outbox tray", "sent"] },
    { emoji: "📥", keywords: ["inbox tray", "received"] },
    { emoji: "📦", keywords: ["package", "box", "delivery"] },
    { emoji: "📫", keywords: ["mailbox", "mail"] },
    { emoji: "📪", keywords: ["mailbox", "empty"] },
    { emoji: "📬", keywords: ["mailbox with mail"] },
    { emoji: "📭", keywords: ["mailbox", "no mail"] },
    { emoji: "📮", keywords: ["postbox", "mail"] },
    { emoji: "📝", keywords: ["memo", "note", "write", "pencil"] },
    { emoji: "📃", keywords: ["page with curl", "document"] },
    { emoji: "📄", keywords: ["page facing up", "document"] },
    { emoji: "📑", keywords: ["bookmark tabs"] },
    { emoji: "📊", keywords: ["bar chart", "graph", "stats"] },
    { emoji: "📈", keywords: ["chart increasing", "growth", "up"] },
    { emoji: "📉", keywords: ["chart decreasing", "down"] },
    { emoji: "🗒️", keywords: ["spiral notepad"] },
    { emoji: "🗓️", keywords: ["spiral calendar"] },
    { emoji: "📆", keywords: ["tear-off calendar", "date"] },
    { emoji: "📅", keywords: ["calendar", "date"] },
    { emoji: "📇", keywords: ["card index", "rolodex"] },
    { emoji: "🗃️", keywords: ["card file box"] },
    { emoji: "🗳️", keywords: ["ballot box", "vote"] },
    { emoji: "🗄️", keywords: ["file cabinet"] },
    { emoji: "📋", keywords: ["clipboard", "paste"] },
    { emoji: "📁", keywords: ["file folder", "directory"] },
    { emoji: "📂", keywords: ["open file folder"] },
    { emoji: "🗂️", keywords: ["card index dividers"] },
    { emoji: "📰", keywords: ["newspaper", "news"] },
    { emoji: "📓", keywords: ["notebook"] },
    { emoji: "📔", keywords: ["notebook with decorative cover"] },
    { emoji: "📒", keywords: ["ledger", "notebook"] },
    { emoji: "📕", keywords: ["closed book", "red"] },
    { emoji: "📗", keywords: ["green book"] },
    { emoji: "📘", keywords: ["blue book"] },
    { emoji: "📙", keywords: ["orange book"] },
    { emoji: "📚", keywords: ["books", "library", "study"] },
    { emoji: "📖", keywords: ["open book", "read"] },
    { emoji: "🔗", keywords: ["link", "chain", "url"] },
    { emoji: "📎", keywords: ["paperclip", "attachment"] },
    { emoji: "🖇️", keywords: ["linked paperclips"] },
    { emoji: "✂️", keywords: ["scissors", "cut"] },
    { emoji: "📐", keywords: ["triangular ruler"] },
    { emoji: "📏", keywords: ["straight ruler", "measure"] },
    { emoji: "🧮", keywords: ["abacus", "calculate"] },
    { emoji: "📌", keywords: ["pushpin", "pin"] },
    { emoji: "📍", keywords: ["round pushpin", "location"] },
    { emoji: "✏️", keywords: ["pencil", "write"] },
    { emoji: "🖊️", keywords: ["pen", "write"] },
    { emoji: "🖋️", keywords: ["fountain pen", "write"] },
    { emoji: "🖌️", keywords: ["paintbrush", "art"] },
    { emoji: "🖍️", keywords: ["crayon", "draw"] },
    { emoji: "🔍", keywords: ["magnifying glass", "search", "zoom"] },
    { emoji: "🔎", keywords: ["magnifying glass right", "search"] },
  ],
};
