//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
import type { EmojiCategory } from "./types";

export const smileys: EmojiCategory = {
  label: "Smileys & People",
  icon: "😊",
  entries: [
    { emoji: "😀", keywords: ["grinning", "happy", "smile"] },
    { emoji: "😃", keywords: ["grinning", "big eyes", "happy"] },
    { emoji: "😄", keywords: ["grinning", "squinting", "happy", "laugh"] },
    { emoji: "😁", keywords: ["beaming", "grin", "happy"] },
    { emoji: "😆", keywords: ["squinting", "laugh", "happy"] },
    { emoji: "😅", keywords: ["sweat", "grinning", "nervous"] },
    { emoji: "🤣", keywords: ["rofl", "rolling", "laughing", "lol"] },
    { emoji: "😂", keywords: ["joy", "crying", "laughing", "tears", "lol"] },
    { emoji: "🙂", keywords: ["slightly smiling", "ok"] },
    { emoji: "🙃", keywords: ["upside down", "sarcasm"] },
    { emoji: "😉", keywords: ["wink", "winking"] },
    { emoji: "😊", keywords: ["blush", "smiling", "happy", "warm"] },
    { emoji: "😇", keywords: ["angel", "halo", "innocent"] },
    { emoji: "🥰", keywords: ["love", "hearts", "adore", "smiling"] },
    { emoji: "😍", keywords: ["heart eyes", "love", "crush"] },
    { emoji: "🤩", keywords: ["star struck", "excited", "wow"] },
    { emoji: "😘", keywords: ["kiss", "blowing kiss", "love"] },
    { emoji: "😗", keywords: ["kissing", "pucker"] },
    { emoji: "☺️", keywords: ["smiling", "relaxed", "happy"] },
    { emoji: "😚", keywords: ["kissing", "closed eyes"] },
    { emoji: "😙", keywords: ["kissing", "smiling eyes"] },
    { emoji: "🥲", keywords: ["smiling", "tear", "sad", "proud"] },
    { emoji: "😋", keywords: ["yummy", "delicious", "tongue"] },
    { emoji: "😛", keywords: ["tongue", "playful"] },
    { emoji: "😜", keywords: ["wink", "tongue", "crazy", "zany"] },
    { emoji: "🤪", keywords: ["zany", "crazy", "wild", "goofy"] },
    { emoji: "😝", keywords: ["squinting", "tongue"] },
    { emoji: "🤑", keywords: ["money", "rich", "dollar"] },
    { emoji: "🤗", keywords: ["hug", "hugging", "open hands"] },
    { emoji: "🤭", keywords: ["hand over mouth", "oops", "giggle"] },
    { emoji: "🫢", keywords: ["open eyes", "hand over mouth", "surprise"] },
    { emoji: "🫣", keywords: ["peeking", "shy", "hiding"] },
    { emoji: "🤫", keywords: ["shh", "quiet", "secret", "shush"] },
    { emoji: "🤔", keywords: ["thinking", "hmm", "consider"] },
    { emoji: "🫡", keywords: ["salute", "respect"] },
    { emoji: "🤐", keywords: ["zipper mouth", "quiet", "secret"] },
    { emoji: "🤨", keywords: ["raised eyebrow", "skeptical", "suspicious"] },
    { emoji: "😐", keywords: ["neutral", "blank", "indifferent"] },
    { emoji: "😑", keywords: ["expressionless", "blank"] },
    { emoji: "😶", keywords: ["no mouth", "silent", "speechless"] },
    { emoji: "🫥", keywords: ["dotted line", "invisible", "hidden"] },
    { emoji: "😏", keywords: ["smirk", "smug", "sly"] },
    { emoji: "😒", keywords: ["unamused", "annoyed", "meh"] },
    { emoji: "🙄", keywords: ["eye roll", "annoyed", "whatever"] },
    { emoji: "😬", keywords: ["grimace", "awkward", "nervous"] },
    { emoji: "🫨", keywords: ["shaking", "shock"] },
    { emoji: "😮‍💨", keywords: ["exhale", "sigh", "relief"] },
    { emoji: "🤥", keywords: ["lying", "pinocchio", "liar"] },
    { emoji: "🫠", keywords: ["melting", "dissolving", "hot"] },
    { emoji: "😌", keywords: ["relieved", "peaceful", "calm"] },
    { emoji: "😔", keywords: ["pensive", "sad", "thoughtful"] },
    { emoji: "😪", keywords: ["sleepy", "tired", "tear"] },
    { emoji: "🤤", keywords: ["drooling", "hungry", "want"] },
    { emoji: "😴", keywords: ["sleeping", "zzz", "tired"] },
    { emoji: "😷", keywords: ["mask", "sick", "medical"] },
    { emoji: "🤒", keywords: ["thermometer", "sick", "fever"] },
    { emoji: "🤕", keywords: ["bandage", "hurt", "injured"] },
    { emoji: "🤢", keywords: ["nauseated", "sick", "green"] },
    { emoji: "🤮", keywords: ["vomiting", "sick", "puke"] },
    { emoji: "🥵", keywords: ["hot", "sweating", "heat"] },
    { emoji: "🥶", keywords: ["cold", "freezing", "ice"] },
    { emoji: "🥴", keywords: ["woozy", "dizzy", "drunk"] },
    { emoji: "😵", keywords: ["dizzy", "knocked out"] },
    { emoji: "😵‍💫", keywords: ["dizzy", "spiral", "confused"] },
    { emoji: "🤯", keywords: ["exploding head", "mind blown", "shocked"] },
    { emoji: "🤠", keywords: ["cowboy", "hat", "yeehaw"] },
    { emoji: "🥳", keywords: ["party", "celebrate", "birthday", "hat"] },
    { emoji: "🥸", keywords: ["disguise", "glasses", "nose"] },
    { emoji: "😎", keywords: ["sunglasses", "cool", "confident"] },
    { emoji: "🤓", keywords: ["nerd", "glasses", "geek"] },
    { emoji: "🧐", keywords: ["monocle", "inspect", "curious"] },
    { emoji: "😕", keywords: ["confused", "puzzled"] },
    { emoji: "🫤", keywords: ["diagonal mouth", "unsure", "meh"] },
    { emoji: "😟", keywords: ["worried", "concerned"] },
    { emoji: "🙁", keywords: ["slightly frowning", "sad"] },
    { emoji: "☹️", keywords: ["frowning", "sad"] },
    { emoji: "😮", keywords: ["open mouth", "surprised"] },
    { emoji: "😯", keywords: ["hushed", "surprised", "stunned"] },
    { emoji: "😲", keywords: ["astonished", "shocked", "wow"] },
    { emoji: "😳", keywords: ["flushed", "embarrassed", "surprised"] },
    { emoji: "🥺", keywords: ["pleading", "puppy eyes", "please"] },
    { emoji: "🥹", keywords: ["holding back tears", "touched", "grateful"] },
    { emoji: "😦", keywords: ["frowning", "open mouth"] },
    { emoji: "😧", keywords: ["anguished", "shocked"] },
    { emoji: "😨", keywords: ["fearful", "scared", "afraid"] },
    { emoji: "😰", keywords: ["anxious", "sweat", "worried"] },
    { emoji: "😥", keywords: ["sad", "relieved", "disappointed"] },
    { emoji: "😢", keywords: ["crying", "sad", "tear"] },
    { emoji: "😭", keywords: ["sobbing", "crying", "wailing", "sad"] },
    { emoji: "😱", keywords: ["screaming", "fear", "horror", "scared"] },
    { emoji: "😖", keywords: ["confounded", "frustrated"] },
    { emoji: "😣", keywords: ["persevering", "struggling"] },
    { emoji: "😞", keywords: ["disappointed", "sad"] },
    { emoji: "😓", keywords: ["downcast", "sweat", "sad"] },
    { emoji: "😩", keywords: ["weary", "tired", "exhausted"] },
    { emoji: "😫", keywords: ["tired", "frustrated"] },
    { emoji: "🥱", keywords: ["yawning", "bored", "tired"] },
    { emoji: "😤", keywords: ["huffing", "angry", "frustrated", "triumph"] },
    { emoji: "😡", keywords: ["angry", "pouting", "mad", "rage"] },
    { emoji: "😠", keywords: ["angry", "mad", "grumpy"] },
    { emoji: "🤬", keywords: ["swearing", "cursing", "angry", "symbols"] },
    { emoji: "😈", keywords: ["devil", "evil", "smiling", "horns"] },
    { emoji: "👿", keywords: ["angry devil", "imp", "evil"] },
    { emoji: "💀", keywords: ["skull", "dead", "death", "skeleton"] },
    { emoji: "☠️", keywords: ["skull crossbones", "death", "danger"] },
    { emoji: "💩", keywords: ["poop", "poo", "pile"] },
    { emoji: "🤡", keywords: ["clown", "joker", "funny"] },
    { emoji: "👹", keywords: ["ogre", "monster", "demon"] },
    { emoji: "👺", keywords: ["goblin", "tengu", "mask"] },
    { emoji: "👻", keywords: ["ghost", "halloween", "spooky"] },
    { emoji: "👽", keywords: ["alien", "ufo", "extraterrestrial"] },
    { emoji: "👾", keywords: ["alien monster", "space invader", "game"] },
    { emoji: "🤖", keywords: ["robot", "machine", "bot"] },
    { emoji: "😺", keywords: ["cat", "smiling", "happy"] },
    { emoji: "😸", keywords: ["cat", "grinning", "happy"] },
    { emoji: "😹", keywords: ["cat", "tears", "joy", "laugh"] },
    { emoji: "😻", keywords: ["cat", "heart eyes", "love"] },
    { emoji: "😼", keywords: ["cat", "smirk", "wry"] },
    { emoji: "😽", keywords: ["cat", "kiss"] },
    { emoji: "🙀", keywords: ["cat", "weary", "surprised"] },
    { emoji: "😿", keywords: ["cat", "crying", "sad"] },
    { emoji: "😾", keywords: ["cat", "pouting", "angry"] },
    { emoji: "🙈", keywords: ["monkey", "see no evil"] },
    { emoji: "🙉", keywords: ["monkey", "hear no evil"] },
    { emoji: "🙊", keywords: ["monkey", "speak no evil"] },
  ],
};
