//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
import type { EmojiCategory } from "./types";

export const symbols: EmojiCategory = {
  label: "Symbols",
  icon: "💟",
  entries: [
    { emoji: "❤️", keywords: ["red heart", "love"] },
    { emoji: "🧡", keywords: ["orange heart", "love"] },
    { emoji: "💛", keywords: ["yellow heart", "love"] },
    { emoji: "💚", keywords: ["green heart", "love"] },
    { emoji: "💙", keywords: ["blue heart", "love"] },
    { emoji: "💜", keywords: ["purple heart", "love"] },
    { emoji: "🖤", keywords: ["black heart", "love"] },
    { emoji: "🤍", keywords: ["white heart", "love"] },
    { emoji: "🤎", keywords: ["brown heart", "love"] },
    { emoji: "❤️‍🔥", keywords: ["heart on fire", "passion"] },
    { emoji: "❤️‍🩹", keywords: ["mending heart", "healing"] },
    { emoji: "💔", keywords: ["broken heart", "sad"] },
    { emoji: "💕", keywords: ["two hearts", "love"] },
    { emoji: "💞", keywords: ["revolving hearts", "love"] },
    { emoji: "💓", keywords: ["beating heart", "love"] },
    { emoji: "💗", keywords: ["growing heart", "love"] },
    { emoji: "💖", keywords: ["sparkling heart", "love"] },
    { emoji: "💘", keywords: ["heart with arrow", "cupid"] },
    { emoji: "💝", keywords: ["heart with ribbon", "gift", "love"] },
    { emoji: "💟", keywords: ["heart decoration", "love"] },
    { emoji: "☮️", keywords: ["peace", "symbol"] },
    { emoji: "✝️", keywords: ["cross", "christian", "religion"] },
    { emoji: "☪️", keywords: ["star and crescent", "islam"] },
    { emoji: "🕉️", keywords: ["om", "hindu", "buddhist"] },
    { emoji: "☸️", keywords: ["wheel of dharma", "buddhism"] },
    { emoji: "✡️", keywords: ["star of david", "jewish"] },
    { emoji: "🔯", keywords: ["six pointed star"] },
    { emoji: "🕎", keywords: ["menorah", "jewish", "hanukkah"] },
    { emoji: "☯️", keywords: ["yin yang", "balance"] },
    { emoji: "☦️", keywords: ["orthodox cross"] },
    { emoji: "🛐", keywords: ["place of worship", "pray"] },
    { emoji: "⛎", keywords: ["ophiuchus", "zodiac"] },
    { emoji: "♈", keywords: ["aries", "zodiac"] },
    { emoji: "♉", keywords: ["taurus", "zodiac"] },
    { emoji: "♊", keywords: ["gemini", "zodiac"] },
    { emoji: "♋", keywords: ["cancer", "zodiac"] },
    { emoji: "♌", keywords: ["leo", "zodiac"] },
    { emoji: "♍", keywords: ["virgo", "zodiac"] },
    { emoji: "♎", keywords: ["libra", "zodiac"] },
    { emoji: "♏", keywords: ["scorpio", "zodiac"] },
    { emoji: "♐", keywords: ["sagittarius", "zodiac"] },
    { emoji: "♑", keywords: ["capricorn", "zodiac"] },
    { emoji: "♒", keywords: ["aquarius", "zodiac"] },
    { emoji: "♓", keywords: ["pisces", "zodiac"] },
    { emoji: "🆔", keywords: ["id", "identity"] },
    { emoji: "⚛️", keywords: ["atom", "science"] },
    { emoji: "🉑", keywords: ["accept", "japanese"] },
    { emoji: "☢️", keywords: ["radioactive", "nuclear"] },
    { emoji: "☣️", keywords: ["biohazard", "danger"] },
    { emoji: "📴", keywords: ["mobile phone off"] },
    { emoji: "📳", keywords: ["vibration mode"] },
    { emoji: "🈶", keywords: ["japanese not free of charge"] },
    { emoji: "🈚", keywords: ["japanese free of charge"] },
    { emoji: "🈸", keywords: ["japanese application"] },
    { emoji: "🈺", keywords: ["japanese open for business"] },
    { emoji: "🈷️", keywords: ["japanese monthly amount"] },
    { emoji: "✴️", keywords: ["eight pointed star"] },
    { emoji: "🆚", keywords: ["vs", "versus", "against"] },
    { emoji: "💮", keywords: ["white flower", "good job"] },
    { emoji: "🉐", keywords: ["japanese bargain"] },
    { emoji: "㊙️", keywords: ["japanese secret"] },
    { emoji: "㊗️", keywords: ["japanese congratulations"] },
    { emoji: "🈴", keywords: ["japanese passing grade"] },
    { emoji: "🈵", keywords: ["japanese no vacancy"] },
    { emoji: "🈹", keywords: ["japanese discount"] },
    { emoji: "🈲", keywords: ["japanese prohibited"] },
    { emoji: "🅰️", keywords: ["a button", "blood type"] },
    { emoji: "🅱️", keywords: ["b button", "blood type"] },
    { emoji: "🆎", keywords: ["ab button", "blood type"] },
    { emoji: "🆑", keywords: ["cl button", "clear"] },
    { emoji: "🅾️", keywords: ["o button", "blood type"] },
    { emoji: "🆘", keywords: ["sos", "help", "emergency"] },
    { emoji: "❌", keywords: ["cross mark", "no", "wrong", "x"] },
    { emoji: "⭕", keywords: ["hollow red circle", "correct"] },
    { emoji: "🛑", keywords: ["stop sign", "halt"] },
    { emoji: "⛔", keywords: ["no entry", "prohibited"] },
    { emoji: "📛", keywords: ["name badge"] },
    { emoji: "🚫", keywords: ["prohibited", "forbidden", "no"] },
    { emoji: "💯", keywords: ["hundred", "perfect", "score", "100"] },
    { emoji: "💢", keywords: ["anger", "angry", "symbol"] },
    { emoji: "♨️", keywords: ["hot springs", "steam"] },
    { emoji: "🚷", keywords: ["no pedestrians"] },
    { emoji: "🚯", keywords: ["no littering"] },
    { emoji: "🚳", keywords: ["no bicycles"] },
    { emoji: "🚱", keywords: ["non-potable water"] },
    { emoji: "🔞", keywords: ["no one under eighteen", "18+"] },
    { emoji: "📵", keywords: ["no mobile phones"] },
    { emoji: "🔇", keywords: ["muted", "no sound"] },
    { emoji: "🔕", keywords: ["bell with slash", "mute"] },
    { emoji: "🔊", keywords: ["speaker high volume", "loud"] },
    { emoji: "🔉", keywords: ["speaker medium volume"] },
    { emoji: "🔈", keywords: ["speaker low volume"] },
    { emoji: "🔔", keywords: ["bell", "notification", "alert"] },
    { emoji: "♻️", keywords: ["recycling", "recycle", "green"] },
    { emoji: "✅", keywords: ["check mark", "yes", "correct", "done"] },
    { emoji: "❎", keywords: ["cross mark button", "no"] },
    { emoji: "〽️", keywords: ["part alternation mark"] },
    { emoji: "❗", keywords: ["exclamation", "warning", "important"] },
    { emoji: "❓", keywords: ["question mark"] },
    { emoji: "❕", keywords: ["white exclamation mark"] },
    { emoji: "❔", keywords: ["white question mark"] },
    { emoji: "‼️", keywords: ["double exclamation mark"] },
    { emoji: "⁉️", keywords: ["exclamation question mark"] },
    { emoji: "🔅", keywords: ["dim button", "brightness low"] },
    { emoji: "🔆", keywords: ["bright button", "brightness high"] },
    { emoji: "⚠️", keywords: ["warning", "caution", "alert"] },
    { emoji: "🚸", keywords: ["children crossing"] },
    { emoji: "🔱", keywords: ["trident", "emblem"] },
    { emoji: "⚜️", keywords: ["fleur-de-lis"] },
    { emoji: "🔰", keywords: ["japanese symbol for beginner"] },
    { emoji: "♿", keywords: ["wheelchair", "accessibility"] },
    { emoji: "🏧", keywords: ["atm sign"] },
    { emoji: "Ⓜ️", keywords: ["circled m", "metro"] },
    { emoji: "🛂", keywords: ["passport control"] },
    { emoji: "🛃", keywords: ["customs"] },
    { emoji: "🛄", keywords: ["baggage claim"] },
    { emoji: "🛅", keywords: ["left luggage"] },
    { emoji: "🔠", keywords: ["input latin uppercase"] },
    { emoji: "🔡", keywords: ["input latin lowercase"] },
    { emoji: "🔢", keywords: ["input numbers"] },
    { emoji: "🔣", keywords: ["input symbols"] },
    { emoji: "🔤", keywords: ["input latin letters"] },
    { emoji: "ℹ️", keywords: ["information", "info"] },
    { emoji: "🆗", keywords: ["ok button"] },
    { emoji: "🆕", keywords: ["new button"] },
    { emoji: "🆙", keywords: ["up button", "upgrade"] },
    { emoji: "🆒", keywords: ["cool button"] },
    { emoji: "🆓", keywords: ["free button"] },
    { emoji: "🆖", keywords: ["ng button", "no good"] },
    { emoji: "🅿️", keywords: ["p button", "parking"] },
    { emoji: "🈁", keywords: ["japanese here"] },
    { emoji: "🈂️", keywords: ["japanese service charge"] },
    { emoji: "🈳", keywords: ["japanese vacancy"] },
    { emoji: "🔃", keywords: ["clockwise arrows", "reload", "refresh"] },
    { emoji: "🔄", keywords: ["counterclockwise arrows", "refresh"] },
    { emoji: "🔙", keywords: ["back arrow"] },
    { emoji: "🔚", keywords: ["end arrow"] },
    { emoji: "🔛", keywords: ["on arrow"] },
    { emoji: "🔜", keywords: ["soon arrow"] },
    { emoji: "🔝", keywords: ["top arrow"] },
    { emoji: "⬆️", keywords: ["up arrow"] },
    { emoji: "⬇️", keywords: ["down arrow"] },
    { emoji: "⬅️", keywords: ["left arrow"] },
    { emoji: "➡️", keywords: ["right arrow"] },
    { emoji: "↗️", keywords: ["up-right arrow"] },
    { emoji: "↘️", keywords: ["down-right arrow"] },
    { emoji: "↙️", keywords: ["down-left arrow"] },
    { emoji: "↖️", keywords: ["up-left arrow"] },
    { emoji: "↕️", keywords: ["up-down arrow"] },
    { emoji: "↔️", keywords: ["left-right arrow"] },
    { emoji: "↩️", keywords: ["right arrow curving left", "undo"] },
    { emoji: "↪️", keywords: ["left arrow curving right", "redo"] },
    { emoji: "⤴️", keywords: ["right arrow curving up"] },
    { emoji: "⤵️", keywords: ["right arrow curving down"] },
    { emoji: "🔀", keywords: ["shuffle", "random"] },
    { emoji: "🔁", keywords: ["repeat", "loop"] },
    { emoji: "🔂", keywords: ["repeat single"] },
    { emoji: "▶️", keywords: ["play button", "start"] },
    { emoji: "⏩", keywords: ["fast forward"] },
    { emoji: "⏭️", keywords: ["next track button"] },
    { emoji: "⏯️", keywords: ["play or pause button"] },
    { emoji: "◀️", keywords: ["reverse button", "back"] },
    { emoji: "⏪", keywords: ["fast reverse", "rewind"] },
    { emoji: "⏮️", keywords: ["last track button"] },
    { emoji: "⏸️", keywords: ["pause button"] },
    { emoji: "⏹️", keywords: ["stop button"] },
    { emoji: "⏺️", keywords: ["record button"] },
    { emoji: "⏏️", keywords: ["eject button"] },
    { emoji: "🎵", keywords: ["musical note", "music", "song"] },
    { emoji: "🎶", keywords: ["musical notes", "music", "singing"] },
    { emoji: "➕", keywords: ["plus", "add"] },
    { emoji: "➖", keywords: ["minus", "subtract"] },
    { emoji: "➗", keywords: ["divide", "division"] },
    { emoji: "✖️", keywords: ["multiply", "times"] },
    { emoji: "♾️", keywords: ["infinity", "forever"] },
    { emoji: "💲", keywords: ["dollar sign", "money"] },
    { emoji: "💱", keywords: ["currency exchange"] },
    { emoji: "™️", keywords: ["trade mark", "tm"] },
    { emoji: "©️", keywords: ["copyright"] },
    { emoji: "®️", keywords: ["registered"] },
    { emoji: "〰️", keywords: ["wavy dash"] },
    { emoji: "➰", keywords: ["curly loop"] },
    { emoji: "➿", keywords: ["double curly loop"] },
    { emoji: "#️⃣", keywords: ["keycap hash", "number sign", "hashtag"] },
    { emoji: "*️⃣", keywords: ["keycap asterisk", "star"] },
    { emoji: "0️⃣", keywords: ["keycap zero", "0"] },
    { emoji: "1️⃣", keywords: ["keycap one", "1"] },
    { emoji: "2️⃣", keywords: ["keycap two", "2"] },
    { emoji: "3️⃣", keywords: ["keycap three", "3"] },
    { emoji: "4️⃣", keywords: ["keycap four", "4"] },
    { emoji: "5️⃣", keywords: ["keycap five", "5"] },
    { emoji: "6️⃣", keywords: ["keycap six", "6"] },
    { emoji: "7️⃣", keywords: ["keycap seven", "7"] },
    { emoji: "8️⃣", keywords: ["keycap eight", "8"] },
    { emoji: "9️⃣", keywords: ["keycap nine", "9"] },
    { emoji: "🔟", keywords: ["keycap ten", "10"] },
    { emoji: "🔶", keywords: ["large orange diamond"] },
    { emoji: "🔷", keywords: ["large blue diamond"] },
    { emoji: "🔸", keywords: ["small orange diamond"] },
    { emoji: "🔹", keywords: ["small blue diamond"] },
    { emoji: "🔺", keywords: ["red triangle up"] },
    { emoji: "🔻", keywords: ["red triangle down"] },
    { emoji: "◾", keywords: ["black medium-small square"] },
    { emoji: "◽", keywords: ["white medium-small square"] },
    { emoji: "⬛", keywords: ["black large square"] },
    { emoji: "⬜", keywords: ["white large square"] },
    { emoji: "🟥", keywords: ["red square"] },
    { emoji: "🟧", keywords: ["orange square"] },
    { emoji: "🟨", keywords: ["yellow square"] },
    { emoji: "🟩", keywords: ["green square"] },
    { emoji: "🟦", keywords: ["blue square"] },
    { emoji: "🟪", keywords: ["purple square"] },
    { emoji: "🟫", keywords: ["brown square"] },
    { emoji: "🔴", keywords: ["red circle"] },
    { emoji: "🟠", keywords: ["orange circle"] },
    { emoji: "🟡", keywords: ["yellow circle"] },
    { emoji: "🟢", keywords: ["green circle"] },
    { emoji: "🔵", keywords: ["blue circle"] },
    { emoji: "🟣", keywords: ["purple circle"] },
    { emoji: "🟤", keywords: ["brown circle"] },
    { emoji: "⚫", keywords: ["black circle"] },
    { emoji: "⚪", keywords: ["white circle"] },
  ],
};
