//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
import type { EmojiCategory } from "./types";

export const travel: EmojiCategory = {
  label: "Travel & Places",
  icon: "✈️",
  entries: [
    { emoji: "🚗", keywords: ["car", "automobile", "vehicle"] },
    { emoji: "🚕", keywords: ["taxi", "cab"] },
    { emoji: "🚙", keywords: ["suv", "car", "vehicle"] },
    { emoji: "🚌", keywords: ["bus", "transit"] },
    { emoji: "🚎", keywords: ["trolleybus", "transit"] },
    { emoji: "🏎️", keywords: ["racing car", "formula", "fast"] },
    { emoji: "🚓", keywords: ["police car"] },
    { emoji: "🚑", keywords: ["ambulance", "emergency"] },
    { emoji: "🚒", keywords: ["fire truck", "engine"] },
    { emoji: "🚐", keywords: ["minibus", "van"] },
    { emoji: "🛻", keywords: ["pickup truck"] },
    { emoji: "🚚", keywords: ["delivery truck", "moving"] },
    { emoji: "🚛", keywords: ["articulated lorry", "truck"] },
    { emoji: "🚜", keywords: ["tractor", "farm"] },
    { emoji: "🛵", keywords: ["motor scooter", "vespa"] },
    { emoji: "🏍️", keywords: ["motorcycle", "motorbike"] },
    { emoji: "🛺", keywords: ["auto rickshaw", "tuk tuk"] },
    { emoji: "🚲", keywords: ["bicycle", "bike", "cycling"] },
    { emoji: "🛴", keywords: ["kick scooter"] },
    { emoji: "🚏", keywords: ["bus stop", "transit"] },
    { emoji: "🛤️", keywords: ["railway track", "train"] },
    { emoji: "🚃", keywords: ["railway car", "train"] },
    { emoji: "🚋", keywords: ["tram car", "trolley"] },
    { emoji: "🚞", keywords: ["mountain railway"] },
    { emoji: "🚝", keywords: ["monorail", "train"] },
    { emoji: "🚄", keywords: ["bullet train", "high speed", "fast"] },
    { emoji: "🚅", keywords: ["bullet train", "shinkansen"] },
    { emoji: "🚆", keywords: ["train"] },
    { emoji: "🚇", keywords: ["metro", "subway"] },
    { emoji: "🚈", keywords: ["light rail"] },
    { emoji: "🚉", keywords: ["station", "train"] },
    { emoji: "✈️", keywords: ["airplane", "plane", "flight", "travel"] },
    { emoji: "🛩️", keywords: ["small airplane"] },
    { emoji: "🛫", keywords: ["departure", "takeoff", "airplane"] },
    { emoji: "🛬", keywords: ["arrival", "landing", "airplane"] },
    { emoji: "🪂", keywords: ["parachute", "skydiving"] },
    { emoji: "💺", keywords: ["seat", "airplane", "chair"] },
    { emoji: "🚁", keywords: ["helicopter", "chopper"] },
    { emoji: "🚀", keywords: ["rocket", "launch", "space"] },
    { emoji: "🛸", keywords: ["ufo", "flying saucer", "alien"] },
    { emoji: "🛶", keywords: ["canoe", "boat", "paddle"] },
    { emoji: "⛵", keywords: ["sailboat", "sailing"] },
    { emoji: "🚤", keywords: ["speedboat", "motorboat"] },
    { emoji: "🛥️", keywords: ["motor boat"] },
    { emoji: "🛳️", keywords: ["passenger ship", "cruise"] },
    { emoji: "⛴️", keywords: ["ferry", "boat"] },
    { emoji: "🚢", keywords: ["ship", "boat", "cruise"] },
    { emoji: "⚓", keywords: ["anchor", "ship", "port"] },
    { emoji: "🪝", keywords: ["hook", "fishing"] },
    { emoji: "⛽", keywords: ["fuel pump", "gas", "petrol"] },
    { emoji: "🚧", keywords: ["construction", "barrier"] },
    { emoji: "🚦", keywords: ["traffic light", "signal"] },
    { emoji: "🚥", keywords: ["horizontal traffic light"] },
    { emoji: "🗺️", keywords: ["world map", "travel"] },
    { emoji: "🗿", keywords: ["moai", "easter island", "statue"] },
    { emoji: "🗽", keywords: ["statue of liberty", "new york"] },
    { emoji: "🗼", keywords: ["tokyo tower", "japan"] },
    { emoji: "🏰", keywords: ["castle", "european"] },
    { emoji: "🏯", keywords: ["japanese castle"] },
    { emoji: "🏟️", keywords: ["stadium", "arena"] },
    { emoji: "🎡", keywords: ["ferris wheel", "amusement"] },
    { emoji: "🎢", keywords: ["roller coaster", "amusement"] },
    { emoji: "🎠", keywords: ["carousel", "merry go round"] },
    { emoji: "⛲", keywords: ["fountain", "park"] },
    { emoji: "⛱️", keywords: ["umbrella", "beach", "sun"] },
    { emoji: "🏖️", keywords: ["beach", "sand", "sun"] },
    { emoji: "🏝️", keywords: ["desert island", "tropical"] },
    { emoji: "🏜️", keywords: ["desert", "sand"] },
    { emoji: "🌋", keywords: ["volcano", "eruption"] },
    { emoji: "⛰️", keywords: ["mountain"] },
    { emoji: "🏔️", keywords: ["snow capped mountain"] },
    { emoji: "🗻", keywords: ["mount fuji", "japan"] },
    { emoji: "🏕️", keywords: ["camping", "tent"] },
    { emoji: "⛺", keywords: ["tent", "camping"] },
    { emoji: "🏠", keywords: ["house", "home"] },
    { emoji: "🏡", keywords: ["house with garden"] },
    { emoji: "🏘️", keywords: ["houses", "neighborhood"] },
    { emoji: "🏚️", keywords: ["derelict house", "abandoned"] },
    { emoji: "🏗️", keywords: ["building construction", "crane"] },
    { emoji: "🏭", keywords: ["factory", "industrial"] },
    { emoji: "🏢", keywords: ["office building"] },
    { emoji: "🏬", keywords: ["department store", "shopping"] },
    { emoji: "🏣", keywords: ["japanese post office"] },
    { emoji: "🏤", keywords: ["post office"] },
    { emoji: "🏥", keywords: ["hospital", "medical"] },
    { emoji: "🏦", keywords: ["bank", "money"] },
    { emoji: "🏨", keywords: ["hotel", "accommodation"] },
    { emoji: "🏪", keywords: ["convenience store", "shop"] },
    { emoji: "🏫", keywords: ["school", "education"] },
    { emoji: "🏩", keywords: ["love hotel"] },
    { emoji: "💒", keywords: ["wedding", "chapel"] },
    { emoji: "🏛️", keywords: ["classical building", "museum"] },
    { emoji: "⛪", keywords: ["church", "religion"] },
    { emoji: "🕌", keywords: ["mosque", "islam"] },
    { emoji: "🕍", keywords: ["synagogue", "jewish"] },
    { emoji: "🛕", keywords: ["hindu temple"] },
    { emoji: "🕋", keywords: ["kaaba", "mecca"] },
    { emoji: "⛩️", keywords: ["shinto shrine", "japan"] },
    { emoji: "🌃", keywords: ["night", "city", "starry"] },
    { emoji: "🌆", keywords: ["cityscape", "sunset"] },
    { emoji: "🌇", keywords: ["sunset", "city"] },
    { emoji: "🌉", keywords: ["bridge at night"] },
    { emoji: "🌌", keywords: ["milky way", "galaxy", "space"] },
    { emoji: "🎆", keywords: ["fireworks", "celebrate"] },
    { emoji: "🎇", keywords: ["sparkler", "fireworks"] },
  ],
};
